package com.kupreychik.parcellapp.enums;

public enum ConfigName {
    COUNT_OF_ACTIVE_PARCELS_PER_COURIER,
    COUNT_OF_ACTIVE_PARCELS_PER_USER,
    MIN_PRICE_PER_ONE_PARCEL,
    MAX_PRICE_PER_ONE_PARCEL,
    MIN_WEIGHT_PER_ONE_PARCEL,
    MAX_WEIGHT_PER_ONE_PARCEL,
    MIN_LENGTH_PER_ONE_PARCEL,
    MAX_LENGTH_PER_ONE_PARCEL,
    MIN_WIDTH_PER_ONE_PARCEL,
    MAX_WIDTH_PER_ONE_PARCEL,
    MIN_HEIGHT_PER_ONE_PARCEL,
    MAX_HEIGHT_PER_ONE_PARCEL,
    PRICE_PER_ONE_KG,
    PRICE_PER_ONE_KM,
    PERCENT_OF_CANCEL_IN_ASSIGNED_STATUS,
    PERCENT_OF_CANCEL_IN_IN_PROGRESS_STATUS,
}
